config/routes.rb
C2earthSystem::Application.routes.draw do
  resources :clients

  resources :company_types

  resources :investigation_types

  resources :structure_types

  resources :sites do
    collection do
      post :import
      post :process_file

    end
    # /sites/7026/projects
    resources :projects, module: :sites
  end



  # namespace :sites, module: :sites do
  #   #   ... get closed_down   localhost/sites/1/closed_down
  #   member do
  #     resources :projects
  #     resources :activities
  #     #get 'projects'
  #   end
  #
  # end

  resources :stakeholder_types

  resources :faults

  resources :companies

  resources :stakeholders

  resources :client_types

  resources :project_managers

  resources :phases

  resources :projects

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "map", to: "pages#map", as: "map"


  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :activities
  belongs_to :fault
  has_many :projects, through: :activities
  has_and_belongs_to_many :structure_types

  geocoded_by :full_street_address
  # geocoded_by :full_street_address, :latitude => :site_lat, :longitude => :site_long
  # geocoded_by :city_location, :latitude => :city_lat, :longitude => :city_long
  # reverse_geocoded_by :latitude, :longitude do |obj, results|
  #   if geo = results.first
  #     obj.address = geo.address
  #   end
  # end

  # # reverse_geocoded_by :city_lat, :city_long

  after_validation :geocode

  def full_street_address
    [address, city, zipcode, state_code, country_code].compact.join(', ')
  end

  def self.import(file)
    csv = CSV.read(file.path, {:encoding => "CP1251:UTF-8", :col_sep => ",", :row_sep => :auto, :headers => false})
    headers = csv[0].map!(&:downcase)
    present_attributes = []
    Site.attribute_names.each do |attribute|
      if headers.include?(attribute)
        present_attributes << attribute
      end
    end
    
    #exception_fields = ["ProjectNumber","ProjectName1","ProjectName2","ProjectManager","InvestigationType","StructureType","ProjectDescription","ProjectPrefix","ProposalDate","ProposalNumber","ReportDate","SiteNumber","StreetName","City","County","Fault","APN","TOMBROBOX","LOC_PAGE","LOC_LONG","LOC_LAT","Vendor","Notes","ClientName","ClientType","ClientAddress","ClientCity","ClientState","ClientZip","ClientWorkPhone","ClientHomePhone","ClientCellPhone","ClientFaxPhone","ClientEmail","ClientNote","ClientName2","ClientType2","ClientNote2","ClientAddress2","ClientCity2","ClientState2","ClientZip2","ClientWorkPhone2","ClientHomePhone2","ClientCellPhone2","ClientFaxPhone2","ClientEmail2","InsPolicyNum","InsCompany","InsContact","InsAddress","InsCity","InsZip","InsPhone","InsFax","InsEmailWeb","ImsNotes","BillName","BillAttention","BillAddress","BillCity","BillState","BillZip","BadPayHistory","StructuralCompany","StructuralEngineer","StructuralInfo","CivilCompany","CivilEngineer","CivilInfo","SurveyCompany","Surveyor","SurveyorInfo","ArchitectCompany","Architect","ArchitectInfo","AttorneyCompany","Attorney","AttorneyInfo","RealestateBuyer","AgentBuyer","BuyerInfo","RealestateSeller","AgentSeller","SellerInfo","KOR1Company","KOR1Contact","KOR1Info","KOR2Company","KOR2contact","KOR2Info","KOR3Company","KOR3Contact","KOR3Info","Consultant1","ConsultantInfo1","Consultant2","ConsultantInfo2","Consultant3","ConsultantInfo3","Keyword","Memo","Title1","Note1","Title2","Note2","Title3","Note3","Title4","Note4","Title5","Note5"]
    #exception_fields -= ["address", "city", "county"]

    #rows = []
    CSV.foreach(file.path, headers: true) do |row|
      row_hash = row.to_hash.only(present_attributes)
      
      #present_attributes.each do |attribute|
      #  row_hash[attribute.to_sym] = row[attribute.to_sym]
      #end
      site = Site.where(row_hash).first || new
      unless site.id.present?
        site.attributes = row_hash
        site.save!
      end
      #rows << row
    end
    #rows = rows.uniq {|r| [r["address"], r["city"], r["county"]]}

    #rows.each do |row|
    #  site = Site.where(address: row["address"], city: row["city"], county: ["county"]).first || new
      # site.attributes = row.to_hash.except(exception_fields.map {|str| "\"#{str.downcase}\""}.join(','))
      # site.attributes = row.to_hash.except(exception_fields)
      # "['#{exception_fields.join("','")}']"
      # site.attributes = row.to_hash.except("ProjectNumber", "ProjectName1", "ProjectName2", "ProjectManager", "InvestigationType", "StructureType", "ProjectDescription", "ProjectPrefix", "ProposalDate", "ProposalNumber", "ReportDate", "SiteNumber", "StreetName", "Fault", "APN", "TOMBROBOX", "LOC_PAGE", "LOC_LONG", "LOC_LAT", "Vendor", "Notes", "ClientName", "ClientType", "ClientAddress", "ClientCity", "ClientState", "ClientZip", "ClientWorkPhone", "ClientHomePhone", "ClientCellPhone", "ClientFaxPhone", "ClientEmail", "ClientNote", "ClientName2", "ClientType2", "ClientNote2", "ClientAddress2", "ClientCity2", "ClientState2", "ClientZip2", "ClientWorkPhone2", "ClientHomePhone2", "ClientCellPhone2", "ClientFaxPhone2", "ClientEmail2", "InsPolicyNum", "InsCompany", "InsContact", "InsAddress", "InsCity", "InsZip", "InsPhone", "InsFax", "InsEmailWeb", "ImsNotes", "BillName", "BillAttention", "BillAddress", "BillCity", "BillState", "BillZip", "BadPayHistory", "StructuralCompany", "StructuralEngineer", "StructuralInfo", "CivilCompany", "CivilEngineer", "CivilInfo", "SurveyCompany", "Surveyor", "SurveyorInfo", "ArchitectCompany", "Architect", "ArchitectInfo", "AttorneyCompany", "Attorney", "AttorneyInfo", "RealestateBuyer", "AgentBuyer", "BuyerInfo", "RealestateSeller", "AgentSeller", "SellerInfo", "KOR1Company", "KOR1Contact", "KOR1Info", "KOR2Company", "KOR2contact", "KOR2Info", "KOR3Company", "KOR3Contact", "KOR3Info", "Consultant1", "ConsultantInfo1", "Consultant2", "ConsultantInfo2", "Consultant3", "ConsultantInfo3", "Keyword", "Memo", "Title1", "Note1", "Title2", "Note2", "Title3", "Note3", "Title4", "Note4", "Title5", "Note5")
      # site.attributes = row.to_hash.except("StructureType", "Fault", "SiteNumber")
      #site.save!
    #end
  end

end

app/controllers/sites/activities_controller.rb
class Sites::ActivitiesController < ApplicationController

  def new
    @activity = Activity.new
  end

  def create
    @site = Site.find(params[:id])

    @activity = @site.activities.build(activity_params)

    if @site.save
      redirect_to sites_projects_path
    else
      render 'new'
    end
  end

  private
    def activity_params
      params.require(:activity).permit(:site_id, :project_id)
    end
end

app/controllers/sites/projects_controller.rb
class Sites::ProjectsController < ApplicationController

  def index
    @site = Site.find(params[:site_id])
    @projects = @site.projects
  end

  def new
    @project = Project.new
  end

  def create
    @site = Site.find(params[:id])

    @project = @site.projects.build(project_params)

    if @site.save
      redirect_to sites_projects_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  private
    def project_params
      params.require(:project).permit(:name, :name_alternate, :number, :prefix, :description)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_site, only: [:show, :edit, :update, :destroy, :projects]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        flash["notice"] = 'Site was successfully created.'
        format.html { redirect_to @site }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def upload
    if params[:file].present?
      # save the file to file system
      #Site.import(params[:file])
      redirect_to import_sites_path(file_name: params[:file].path)
    else
      redirect_to sites_path, alert: "No file specified."
    end
  end
  
  def import
    # get headers from csv
    csv = CSV.read(params[:file].path, {:encoding => "CP1251:UTF-8", :col_sep => ",", :row_sep => :auto, :headers => false})
    @file_path = params[:file].path
    @headers = csv[0]
    
    @site_attributes = Site.attribute_names
  end
  
  def process_file
    selects = params[:selects]
    matched_headers = Hash.new # { city: "header_city" }
    csv = CSV.read(params[:file_path], {:encoding => "CP1251:UTF-8", :col_sep => ",", :row_sep => :auto, :headers => false})
    
    selects.each do |key, value|
      unless value.blank?
        matched_headers[key] = value #key = csv header, value = site attribute name
      end
    end
    
    CSV.foreach(params[:file_path], headers: true) do |row|
      
      row_hash = row.to_hash
      site = Site.new
      matched_headers.each do |key, value|
        site[value.to_sym] = row_hash[key]
      end
      
      site.save!
    end
    
    redirect_to sites_path
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def lookup
    if params[:city]
      @sites = Site.lookup(params[:city])
    else
      @sites = Site.lookup
    end
  end

  def lookup_address
    #@target = Geocoder.coordinates(params[:address]) #[1123,232323]
    # @sites = Site.near(params[:address], 5)
    # @hash = Gmaps4rails.build_markers(@sites) do |site, marker|
    #   marker.lat site.latitude
    #   marker.lng site.longitude
    #   marker.infowindow "test string"
    # end
    @address = params[:address]
  end

  # GET /sites/id/projects
  def projects
    @projects = @site.projects
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:address, :city, :county, :loc_page, :loc_longitude, :loc_latitude, :apn, :tombrobox, :fault_id)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.haml
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      %ul
        - @site.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :county
    = f.text_field :county
  .field
    = f.label :tombrobox
    = f.text_field :tombrobox
  .field
    = f.label :fault_id
    = f.select :fault_id, Fault.all.map{|f| [f.name, f.id]}
  .actions
    = f.submit 'Save'

app/views/sites/edit.html.haml
%h1 Editing site

= render 'form'

= link_to 'Show', @site
\|
= link_to 'Back', sites_path

app/views/sites/import.html.haml
= form_tag process_file_sites_path, method: :post do
  = hidden_field_tag :file_path, @file_path
  %table
    %tr
      %th
        CSV Header
      %th
        Site attribute
  
    - @headers.each_with_index do |header, index|
      %tr
        %td
          = header
        %td
          = select_tag "selects[#{header}]", options_for_select(@site_attributes), include_blank: true

  = submit_tag "Process"

app/views/sites/index.html.haml
%h1 Listing sites

= form_tag import_sites_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

%table
  %tr
    %th Address
    %th City
    %th County
    %th Tombrobox
    %th Fault
    %th
    %th
    %th

  - @sites.each do |site|
    %tr
      %td= site.address
      %td= site.city
      %td= site.county
      %td= site.tombrobox
      %td= site.try(:fault).try(:name)
      %td= link_to 'Show', site
      %td= link_to 'Edit', edit_site_path(site)
      %td= link_to 'Destroy', site, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Site', new_site_path

app/views/sites/lookup_address.html.haml
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>

<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<div id='map-canvas' style='width:100%;min-height:400px;'></div>


:javascript
  var geocoder;
  var target_coords;
  geocoder = new google.maps.Geocoder();

  geocoder.geocode( { 'address': "#{@address}" }, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        target_coords = results[0].geometry.location;
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });

  function build() {
    handler = Gmaps.build('Google');
    handler.buildMap({
      provider: {
        // pass in other Google Maps API options here
        disableDefaultUI: true,
        mapTypeID: google.maps.MapTypeId.TERRAIN
      },
      internal: {id: 'map-canvas'}},

      function (){
        handler.map.centerOn(target_coords);
        new google.maps.Marker({
          position: new google.maps.LatLng(target_coords),
          map: handler.map,
          title: 'Hello World!'
        });
      }
    );


  }

  // create a marker object for each item
  function createMarker(val, map) {
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(val.latitude, val.longitude),
      map: map,
      title: 'Hello World!'
    });
  }

  google.maps.event.addDomListener(window, 'resize', build);
  google.maps.event.addDomListener(window, 'load', build);

app/views/sites/new.html.haml
%h1 New site

= render 'form'

= link_to 'Back', sites_path

app/views/sites/projects.html.haml
%h1 Listing projects

%table
  %tr
    %th Name




  - @projects.each do |project|
    %tr
      %td= project.name
      

app/views/sites/show.html.haml
%p
  %b Structure type:
  %ul
    - @site.structure_types.each do |structure|
      %li= structure.name
%p
  %b Address:
  = @site.address
%p
  %b City:
  = @site.city
%p
  %b County:
  = @site.county
%p
  %b Tombrobox:
  = @site.tombrobox
- if @site.fault.present?
  %p
    %b Fault:
    = @site.fault.name

= link_to 'Edit', edit_site_path(@site)
\|
= link_to 'Back', sites_path